name = "zensim-web"
compatibility_date = "2026-09-01"

routes = [
  { pattern = "zensimlabs.com", custom_domain = true },
  { pattern = "www.zensimlabs.com", custom_domain = true },
]

[assets]
directory = "./out"
not_found_handling = "404-page"
